### ISSUE TITLE
Crash when mux receives AnalyticsCollector.onLoadCompleted

### ISSUE THREAD

**Issue by zilinx** [muxinc/mux-stats-sdk-exoplayer#119]
The project uses ExoPlayer `2.13.3` 
Mux version `2.4.9`  for ExoPlayer `2.13.1`

I won't go into details here because I bet it's something wrong with my initialisation (demo works fine for seemingly similar setup). I would appreciate if you could help me deciphering this obfuscated stacktrace. 
By the way, is there no way to de-obfuscate these stacktraces? It makes it really difficult to troubleshoot.  
Thanks!

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mux.stats.sdk.core.model.a.a(java.lang.Long)' on a null object reference
        at com.mux.stats.sdk.muxstats.e$c.a(Unknown Source:12)
        at com.mux.stats.sdk.muxstats.e$e.a(Unknown Source:0)
        at com.mux.stats.sdk.muxstats.e$d.a(Unknown Source:29)
        at com.mux.stats.sdk.muxstats.MuxStatsExoPlayer.onLoadCompleted(Unknown Source:16)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.lambda$onLoadCompleted$28(AnalyticsCollector.java:503)
        at com.google.android.exoplayer2.analytics.-$$Lambda$AnalyticsCollector$LCUClj88hG_1RJ03wPFhEhogQu4.invoke(Unknown Source:8)
        at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:297)
        at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:184)
        at com.google.android.exoplayer2.util.-$$Lambda$ListenerSet$NbKDn9xtItiyMgYZmjIx_Sv1FFQ.run(Unknown Source:6)
        at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:205)
        at com.google.android.exoplayer2.util.ListenerSet.sendEvent(ListenerSet.java:220)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.sendEvent(AnalyticsCollector.java:797)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.onLoadCompleted(AnalyticsCollector.java:500)
        at com.google.android.exoplayer2.source.MediaSourceEventListener$EventDispatcher.lambda$loadCompleted$1$MediaSourceEventListener$EventDispatcher(MediaSourceEventListener.java:301)
        at com.google.android.exoplayer2.source.-$$Lambda$MediaSourceEventListener$EventDispatcher$ZuTEoXsbK3i0dfIxRwW-S0zQ6UA.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by jsanford8** [comment]
Hi @zilinx - sorry you're running into this. Can you please try with 2.4.10 which was just released last night to see if this is still happening? We fixed an issue just like this in that release.

**Comment by zilinx** [comment]
Indeed it looks like `2.4.10` fixed the issue. Thank you!
I also noticed there is a mapping file attached to the release, so I can use that if I need to troubleshoot in the future. My apologies, I didn't notice the mapping file earlier.

Again, thank you for your help and swift reply 👍

**Comment by jsanford8** [comment]
No worries, glad that fixed the issue! Let us know if you see any other issues!
