### ISSUE TITLE
Mux should not set VideoFrameMetadataListener.

### ISSUE THREAD

**Issue by zilinx** [muxinc/mux-stats-sdk-exoplayer#126]
Installed version: `2.4.10`

Mux creates its own implementation of `VideoFrameMetadataListener` inside [`MuxBasePlayer`](https://github.com/muxinc/mux-stats-sdk-exoplayer/blob/49805a2ebfd85e9bdfa0959ca56cfb71cfc0e11a/MuxExoPlayer/src/main/java/com/mux/stats/sdk/muxstats/MuxBaseExoPlayer.java#L125) and then [sets it](https://github.com/muxinc/mux-stats-sdk-exoplayer/blob/49805a2ebfd85e9bdfa0959ca56cfb71cfc0e11a/MuxExoPlayer/src/main/java/com/mux/stats/sdk/muxstats/MuxBaseExoPlayer.java#L388) on the player's video component. 

This hijacks the use of that callback outside of Mux. From ExoPlayer's documentation ([source](https://github.com/google/ExoPlayer/blob/b2333c86c1eac9a1f95992960a8495f1e5b79200/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayer.java#L270)): 

> This method is intended to be called by the same component that sets the {@link Surface} onto which video will be rendered. If using ExoPlayer's standard UI components, this method should not be called directly from application code.

It should be clear that given above, Mux is not the right place to set `VideoFrameMetadataListener`. 

- The best solution would be to not set this listener in Mux. As ExoPlayer's documentation mentions further, it is used by ExoPlayer's standard UI components, meaning working around any solutions would be cumbersome. 

- At the very least Mux should provide a way to share the callback with other components.

**Comment by zilinx** [comment]
Related - using Mux with the newest version of ExoPlayer (`2.14.2`) will cause a crash when trying to set `VideoFrameMetadataListener`:

> java.lang.NoSuchMethodError: No interface method getVideoComponent()Lcom/google/android/exoplayer2/Player$VideoComponent; in class Lcom/google/android/exoplayer2/ExoPlayer; or its super classes (declaration of 'com.google.android.exoplayer2.ExoPlayer' appears in /data/app/...-ZUjJ0C83sJAPkvP0wtxqrg==/base.apk)
        at com.mux.stats.sdk.muxstats.e.setPlaybackHeadUpdateInterval(Unknown Source:19)
        at com.mux.stats.sdk.muxstats.e.configurePlaybackHeadUpdateInterval(Unknown Source:66)
        at com.mux.stats.sdk.muxstats.MuxStatsExoPlayer.onTracksChanged(Unknown Source:5)
        at com.mux.stats.sdk.muxstats.MuxStatsExoPlayer.onTracksChanged(Unknown Source:0)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.lambda$onTracksChanged$37(AnalyticsCollector.java:609)
        at com.google.android.exoplayer2.analytics.-$$Lambda$AnalyticsCollector$aTVYLfilZOP2VdswqUqkqxZmwO8.invoke(Unknown Source:8)
        at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:283)
        at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:170)
        at com.google.android.exoplayer2.util.-$$Lambda$ListenerSet$NbKDn9xtItiyMgYZmjIx_Sv1FFQ.run(Unknown Source:6)
        at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:191)
        at com.google.android.exoplayer2.util.ListenerSet.sendEvent(ListenerSet.java:206)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.sendEvent(AnalyticsCollector.java:844)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.onTracksChanged(AnalyticsCollector.java:606)
        at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$11(ExoPlayerImpl.java:1277)
        at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$-gdbQTAYKRew2vYJ0AuWh_XJyh0.invoke(Unknown Source:6)
        at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:283)
        at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:170)
        at com.google.android.exoplayer2.util.-$$Lambda$ListenerSet$NbKDn9xtItiyMgYZmjIx_Sv1FFQ.run(Unknown Source:6)
        at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:191)
        at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1340)
        at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:1175)
        at com.google.android.exoplayer2.ExoPlayerImpl.lambda$new$1$ExoPlayerImpl(ExoPlayerImpl.java:216)
        at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$nOBJYkeEQ2uz3sBKLToLWmzrgZk.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by jsanford8** [comment]
Hi @zilinx - thanks for submitting this! Right now we don't have support for r2.14.x, but we're working on it. Right now, you'll need to use r2.13.x or older until we have support for r2.14.x

**Comment by zilinx** [comment]
Ok, thank you. The new version crash was just a side note - the main issue is still relevant, so I'll keep it open.
Do you have an estimate when support for 2.14.x will come out?

**Comment by skidder** [comment]
@zilinx we've fixed this in https://github.com/muxinc/mux-stats-sdk-exoplayer/releases/tag/v2.4.12

Please give it a try and let us know how it goes. Thanks again for the bug report!

**Comment by zilinx** [comment]
Thank you, checked on 2.4.13, it works well as far as the `VideoFrameMetadataListener` is concerned. 
Now just waiting for ExoPlayer 2.14.x support :)

**Comment by skidder** [comment]
> Now just waiting for ExoPlayer 2.14.x support :)

@zilinx You got it, we've added ExoPlayer 2.14.x support in our 2.4.14 SDK release!

**Comment by zilinx** [comment]
Awesome, thank you! 🎉
