### ISSUE TITLE
Mux init crash when use ExoPlayerImpl

### ISSUE THREAD

**Issue by szhangbiao** [muxinc/mux-stats-sdk-exoplayer#44]
I'm use [ExoMedia](https://github.com/brianwernick/ExoMedia) library on my project that use ExoPlayerFactory.newInstance create player instance [you can check here](https://github.com/brianwernick/ExoMedia/blob/759adcf670882a057df1236850d406a1f783f08a/library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/ExoMediaPlayer.java#L172)
  
```
java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.android.exoplayer2.Player$VideoComponent.setVideoFrameMetadataListener(com.google.android.exoplayer2.video.VideoFrameMetadataListener)' on a null object reference
        at com.mux.stats.sdk.muxstats.e.<init>()
        at com.mux.stats.sdk.muxstats.MuxStatsExoPlayer.<init>()
        at com.mux.stats.sdk.muxstats.MuxStatsExoPlayer.<init>()
        at com.fiton.android.ui.inprogress.InProgressActivity.lambda$initMux$8(InProgressActivity.java:874)
        at com.fiton.android.ui.inprogress.-$$Lambda$InProgressActivity$5y8FZVwFcHxLWDh10AV5SP_HDN8.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7229)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by stevenlyons** [comment]
Hi szhangbiao, good to hear from you. Is Mux Data already integrated with the ExoMedia library or are you trying to build the integration?

**Comment by szhangbiao** [comment]
Trying build the integration that Exoplayer base on more than or equals 2.9.6

**Comment by skidder** [comment]
@szhangbiao can you report on whether this exception is still happening? If not, we'll close out this issue since it's been over 1 year since it was opened.

**Comment by skidder** [comment]
Closing due to inactivity
