### ISSUE TITLE
Application crashing in onAdEvent with 2.11.1 AAR

### ISSUE THREAD

**Issue by Discovery-JSwapnil** [muxinc/mux-stats-sdk-exoplayer#55]
We are using `mux-r2.11.1.aar` and `Exoplayer IMA extension 2.11.0` in our project. Sometimes while trying to play videos, this crash is occurring. Kindly helps us in understanding reason for this crash.

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
       at com.mux.stats.sdk.muxstats.a.onAdEvent(a.java:4)
       at com.google.ads.interactivemedia.v3.internal.acv.a(acv.java:70)
       at com.google.ads.interactivemedia.v3.internal.acv.a(acv.java:108)
       at com.google.ads.interactivemedia.v3.internal.acl.a(acl.java:63)
       at com.google.ads.interactivemedia.v3.internal.aeb.e(aeb.java:174)
       at com.google.ads.interactivemedia.v3.internal.aeb.a(aeb.java:5)
       at com.google.ads.interactivemedia.v3.internal.adz.b(adz.java:42)
       at com.google.ads.interactivemedia.v3.internal.aea.shouldOverrideUrlLoading(aea.java:4)
       at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:77)
       at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:16)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:326)
       at android.os.Looper.loop(Looper.java:181)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by stevenlyons** [comment]
Hi @Discovery-JSwapnil, can you tell me what version of the Mux Core and ExoPlayer plugins you are using when getting this error? Based on your description, sounds like you are testing with ExoPlayer 2.11 but we don't have a version of the SDKs with that string. The specific version of the Mux SDK would help.

**Comment by Discovery-JSwapnil** [comment]
Hi @stevenlyons I am using latest [v2.0.0](https://github.com/muxinc/mux-stats-sdk-exoplayer/releases/tag/v2.0.0) version of the Mux SDK (`mux-r2.11.1.aar`) with `Exoplayer 2.11.0` and `IMA extension SDK 2.11.0`

**Comment by stevenlyons** [comment]
Thanks much, we will take a look and get back to you.

**Comment by tomkordic** [comment]
@Discovery-JSwapnil Can you think of the steps on how to reproduce this bug ?

**Comment by Discovery-JSwapnil** [comment]
> @Discovery-JSwapnil Can you think of the steps on how to reproduce this bug ?

Hi @tomkordic  steps to reproduce are as follows:
1. Play any video which has IMA ads.
2. As soon as ads start playing, start new video.
3. We are releasing exoplayer and creating new one in this case, hence we are calling `muxStatsExoplayer.release()` while releasing and destroying exoplayer. Here crash happens.

If we do not call `muxStatsExoplayer.release()` then this crash does not come. I think it is happening because IMAads listener is not removed in release, hence it is crashing in onAdEvent().

**Comment by tomkordic** [comment]
@Discovery-JSwapnil Thanks for the intel, I think I found the issue, fix should be part of the next release, in the mean time feel free to use this branch: https://github.com/muxinc/mux-stats-sdk-exoplayer/tree/AdsImaSDKListener_crash_fix it contains the fix to your problem.

**Comment by Discovery-JSwapnil** [comment]
Thank you @tomkordic We also got same crash on line 59 of AdsImaSDKListener. Can you help us with possible date of next release? This is very critical issue for us.

**Comment by tomkordic** [comment]
@Discovery-JSwapnil Can you share the crash log please

**Comment by Discovery-JSwapnil** [comment]
> @Discovery-JSwapnil Can you share the crash log please

Yes @tomkordic Here it is:

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
       at com.mux.stats.sdk.muxstats.a.onAdEvent(:59)
       at com.google.ads.interactivemedia.v3.internal.acv.a(IMASDK:70)
       at com.google.ads.interactivemedia.v3.internal.acv.a(IMASDK:108)
       at com.google.ads.interactivemedia.v3.internal.acl.a(IMASDK:63)
       at com.google.ads.interactivemedia.v3.internal.aeb.e(IMASDK:174)
       at com.google.ads.interactivemedia.v3.internal.aeb.a(IMASDK:5)
       at com.google.ads.interactivemedia.v3.internal.adz.b(IMASDK:42)
       at com.google.ads.interactivemedia.v3.internal.aea.shouldOverrideUrlLoading(IMASDK:4)
       at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:83)
       at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-TrichromeWebViewGoogle.aab-stable-424011033:16)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:336)
       at android.os.Looper.loop(Looper.java:174)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by tomkordic** [comment]
@Discovery-JSwapnil Can you please try the code from the branch I shared and see if the issue is still present, I will do some testing on my side using the test scenario you described.

**Comment by Discovery-JSwapnil** [comment]
@tomkordic Above crash is not coming now when I tried AAR from branch you mentioned, but getting another issue, when tried to switch between wifi and cellular 2-3 times.

E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #11
E/MuxNetworkRequests: Task android.os.AsyncTask$3@f305364 rejected from java.util.concurrent.ThreadPoolExecutor@f77209a[Running, pool size = 17, active threads = 17, queued tasks = 128, completed tasks = 68]
    java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@f305364 rejected from java.util.concurrent.ThreadPoolExecutor@f77209a[Running, pool size = 17, active threads = 17, queued tasks = 128, completed tasks = 68]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2085)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)

**Comment by kai-sarawut** [comment]
I got exactly same exception with version 2.0.0 (mux-r2.11.1.aar). For my case, this will occur when open application with deep link navigating to player page.

**Comment by kai-sarawut** [comment]
> We are using `mux-r2.11.1.aar` and `Exoplayer IMA extension 2.11.0` in our project. Sometimes while trying to play videos, this crash is occurring. Kindly helps us in understanding reason for this crash.
> 
> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
> at com.mux.stats.sdk.muxstats.a.onAdEvent(a.java:4)
> at com.google.ads.interactivemedia.v3.internal.acv.a(acv.java:70)
> at com.google.ads.interactivemedia.v3.internal.acv.a(acv.java:108)
> at com.google.ads.interactivemedia.v3.internal.acl.a(acl.java:63)
> at com.google.ads.interactivemedia.v3.internal.aeb.e(aeb.java:174)
> at com.google.ads.interactivemedia.v3.internal.aeb.a(aeb.java:5)
> at com.google.ads.interactivemedia.v3.internal.adz.b(adz.java:42)
> at com.google.ads.interactivemedia.v3.internal.aea.shouldOverrideUrlLoading(aea.java:4)
> at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:77)
> at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:16)
> at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
> at android.os.MessageQueue.next(MessageQueue.java:326)
> at android.os.Looper.loop(Looper.java:181)
> at android.app.ActivityThread.main(ActivityThread.java:7073)
> at java.lang.reflect.Method.invoke(Method.java)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

I got exactly same exception with version 2.0.0 (mux-r2.11.1.aar). For my case, this will occur when I try to open application with deep link navigating to player page.
